/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerWelcomeRouteImport } from './routes/customer.welcome'
import { Route as CustomerSplashRouteImport } from './routes/customer.splash'
import { Route as CustomerOtpRouteImport } from './routes/customer.otp'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerWelcomeRoute = CustomerWelcomeRouteImport.update({
  id: '/customer/welcome',
  path: '/customer/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSplashRoute = CustomerSplashRouteImport.update({
  id: '/customer/splash',
  path: '/customer/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOtpRoute = CustomerOtpRouteImport.update({
  id: '/customer/otp',
  path: '/customer/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/otp': typeof CustomerOtpRoute
  '/customer/splash': typeof CustomerSplashRoute
  '/customer/welcome': typeof CustomerWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/otp': typeof CustomerOtpRoute
  '/customer/splash': typeof CustomerSplashRoute
  '/customer/welcome': typeof CustomerWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/otp': typeof CustomerOtpRoute
  '/customer/splash': typeof CustomerSplashRoute
  '/customer/welcome': typeof CustomerWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer/login'
    | '/customer/otp'
    | '/customer/splash'
    | '/customer/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer/login'
    | '/customer/otp'
    | '/customer/splash'
    | '/customer/welcome'
  id:
    | '__root__'
    | '/'
    | '/customer/login'
    | '/customer/otp'
    | '/customer/splash'
    | '/customer/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerOtpRoute: typeof CustomerOtpRoute
  CustomerSplashRoute: typeof CustomerSplashRoute
  CustomerWelcomeRoute: typeof CustomerWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/welcome': {
      id: '/customer/welcome'
      path: '/customer/welcome'
      fullPath: '/customer/welcome'
      preLoaderRoute: typeof CustomerWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/splash': {
      id: '/customer/splash'
      path: '/customer/splash'
      fullPath: '/customer/splash'
      preLoaderRoute: typeof CustomerSplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/otp': {
      id: '/customer/otp'
      path: '/customer/otp'
      fullPath: '/customer/otp'
      preLoaderRoute: typeof CustomerOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerOtpRoute: CustomerOtpRoute,
  CustomerSplashRoute: CustomerSplashRoute,
  CustomerWelcomeRoute: CustomerWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
